// Generated by listgen. DO NOT EDIT.
// Command: listgen -package catena -list-type sourcelist -value-type *memorySource -cmp "if a.name < b.name {return -1}; if a.name > b.name {return 1}; return 0;"

package catena

import (
	"errors"
	"fmt"
	"sync/atomic"
	"unsafe"
)

var (
	ErrsourcelistValueExists   = errors.New("catena (sourcelist): value exists")
	ErrsourcelistValueNotFound = errors.New("catena (sourcelist): value does not exist")
)

type sourcelist struct {
	head unsafe.Pointer
	size int32
}

type sourcelistNode struct {
	val  *memorySource
	next unsafe.Pointer
}

type sourcelistIterator struct {
	list    *sourcelist
	current *sourcelistNode
	valid   bool
}

func sourcelistCmp(a, b *memorySource) int {
	if a.name < b.name {
		return -1
	}
	if a.name > b.name {
		return 1
	}
	return 0
}

// NewList returns a lock-free ordered list with values of type *memorySource.
func Newsourcelist() *sourcelist {
	return &sourcelist{}
}

// Insert inserts v into the list in order. An error is returned if v is already present.
func (l *sourcelist) Insert(v *memorySource) error {
	n := &sourcelistNode{
		val:  v,
		next: nil,
	}

HEAD:
	headPtr := atomic.LoadPointer(&l.head)

	if headPtr == nil {
		if !atomic.CompareAndSwapPointer(&l.head, headPtr, unsafe.Pointer(n)) {
			goto HEAD
		}

		atomic.AddInt32(&l.size, 1)
		return nil
	}

	headNode := (*sourcelistNode)(headPtr)
	if sourcelistCmp(headNode.val, n.val) > 0 {
		n.next = headPtr
		if !atomic.CompareAndSwapPointer(&l.head, headPtr, unsafe.Pointer(n)) {
			goto HEAD
		}

		atomic.AddInt32(&l.size, 1)
		return nil
	}

	if sourcelistCmp(headNode.val, n.val) == 0 {
		return ErrsourcelistValueExists
	}

NEXT:
	nextPtr := atomic.LoadPointer(&headNode.next)
	if nextPtr == nil {
		if !atomic.CompareAndSwapPointer(&headNode.next, nextPtr, unsafe.Pointer(n)) {
			goto NEXT
		}

		atomic.AddInt32(&l.size, 1)
		return nil
	}

	nextNode := (*sourcelistNode)(nextPtr)
	if sourcelistCmp(nextNode.val, n.val) > 0 {
		n.next = nextPtr
		if !atomic.CompareAndSwapPointer(&headNode.next, nextPtr, unsafe.Pointer(n)) {
			goto NEXT
		}

		atomic.AddInt32(&l.size, 1)
		return nil
	}

	if sourcelistCmp(nextNode.val, n.val) == 0 {
		return ErrsourcelistValueExists
	}

	headNode = nextNode
	goto NEXT
}

// Remove removes v from the list. An error is returned if v is not present.
func (l *sourcelist) Remove(v *memorySource) error {
HEAD:
	headPtr := atomic.LoadPointer(&l.head)

	if headPtr == nil {
		return ErrsourcelistValueNotFound
	}

	headNode := (*sourcelistNode)(headPtr)

	if sourcelistCmp(headNode.val, v) == 0 {
		nextPtr := atomic.LoadPointer(&headNode.next)
		if !atomic.CompareAndSwapPointer(&l.head, headPtr, nextPtr) {
			goto HEAD
		}

		atomic.AddInt32(&l.size, -1)
		return nil
	}

NEXT:
	nextPtr := atomic.LoadPointer(&headNode.next)
	if nextPtr == nil {
		return ErrsourcelistValueNotFound
	}

	nextNode := (*sourcelistNode)(nextPtr)

	if sourcelistCmp(nextNode.val, v) > 0 {
		return ErrsourcelistValueNotFound
	}

	if sourcelistCmp(nextNode.val, v) == 0 {
		replacementPtr := atomic.LoadPointer(&nextNode.next)
		if !atomic.CompareAndSwapPointer(&headNode.next, nextPtr, replacementPtr) {
			goto NEXT
		}

		atomic.AddInt32(&l.size, -1)
		return nil
	}

	headNode = nextNode
	goto NEXT
}

// Size returns the number of elements currently in the list.
func (l *sourcelist) Size() int {
	return int(atomic.LoadInt32(&l.size))
}

// NewIterator returns a new iterator. Values can be read
// after Next is called.
func (l *sourcelist) NewIterator() *sourcelistIterator {
	return &sourcelistIterator{
		list:  l,
		valid: true,
	}
}

// Next positions the iterator at the next node in the list.
// Next will be positioned at the head on the first call.
// The return value will be true if a value can be read from the list.
func (i *sourcelistIterator) Next() bool {
	if !i.valid {
		return false
	}

	if i.current == nil {
		if i.list.head == nil {
			i.valid = false
			return false
		}

		i.current = (*sourcelistNode)(i.list.head)
		return true
	}

	i.current = (*sourcelistNode)(i.current.next)

	i.valid = i.current != nil
	return i.valid
}

// Value reads the value from the current node of the iterator.
// An error is returned if a value cannot be retrieved.
func (i *sourcelistIterator) Value() (*memorySource, error) {
	var v *memorySource

	if i.current == nil {
		return v, ErrsourcelistValueNotFound
	}

	return i.current.val, nil
}

// String returns the string representation of the list.
func (l *sourcelist) String() string {
	output := ""

	if l.head == nil {
		return output
	}

	i := l.NewIterator()

	for i.Next() {
		v, _ := i.Value()
		output += fmt.Sprintf("%v ", v)
	}

	return output
}
