// Generated by listgen. DO NOT EDIT.
// Command: listgen -package catena -list-type pointList -value-type Point -cmp "return int(a.Timestamp-b.Timestamp)"

package catena

import (
	"errors"
	"fmt"
	"sync/atomic"
	"unsafe"
)

var (
	ErrpointListValueExists   = errors.New("catena (pointList): value exists")
	ErrpointListValueNotFound = errors.New("catena (pointList): value does not exist")
)

type pointList struct {
	head unsafe.Pointer
	size int32
}

type pointListNode struct {
	val  Point
	next unsafe.Pointer
}

type pointListIterator struct {
	list    *pointList
	current *pointListNode
	valid   bool
}

func pointListCmp(a, b Point) int {
	return int(a.Timestamp - b.Timestamp)
}

// NewList returns a lock-free ordered list with values of type Point.
func NewpointList() *pointList {
	return &pointList{}
}

// Insert inserts v into the list in order. An error is returned if v is already present.
func (l *pointList) Insert(v Point) error {
	n := &pointListNode{
		val:  v,
		next: nil,
	}

HEAD:
	headPtr := atomic.LoadPointer(&l.head)

	if headPtr == nil {
		if !atomic.CompareAndSwapPointer(&l.head, headPtr, unsafe.Pointer(n)) {
			goto HEAD
		}

		atomic.AddInt32(&l.size, 1)
		return nil
	}

	headNode := (*pointListNode)(headPtr)
	if pointListCmp(headNode.val, n.val) > 0 {
		n.next = headPtr
		if !atomic.CompareAndSwapPointer(&l.head, headPtr, unsafe.Pointer(n)) {
			goto HEAD
		}

		atomic.AddInt32(&l.size, 1)
		return nil
	}

	if pointListCmp(headNode.val, n.val) == 0 {
		return ErrpointListValueExists
	}

NEXT:
	nextPtr := atomic.LoadPointer(&headNode.next)
	if nextPtr == nil {
		if !atomic.CompareAndSwapPointer(&headNode.next, nextPtr, unsafe.Pointer(n)) {
			goto NEXT
		}

		atomic.AddInt32(&l.size, 1)
		return nil
	}

	nextNode := (*pointListNode)(nextPtr)
	if pointListCmp(nextNode.val, n.val) > 0 {
		n.next = nextPtr
		if !atomic.CompareAndSwapPointer(&headNode.next, nextPtr, unsafe.Pointer(n)) {
			goto NEXT
		}

		atomic.AddInt32(&l.size, 1)
		return nil
	}

	if pointListCmp(nextNode.val, n.val) == 0 {
		return ErrpointListValueExists
	}

	headNode = nextNode
	goto NEXT
}

// Remove removes v from the list. An error is returned if v is not present.
func (l *pointList) Remove(v Point) error {
HEAD:
	headPtr := atomic.LoadPointer(&l.head)

	if headPtr == nil {
		return ErrpointListValueNotFound
	}

	headNode := (*pointListNode)(headPtr)

	if pointListCmp(headNode.val, v) == 0 {
		nextPtr := atomic.LoadPointer(&headNode.next)
		if !atomic.CompareAndSwapPointer(&l.head, headPtr, nextPtr) {
			goto HEAD
		}

		atomic.AddInt32(&l.size, -1)
		return nil
	}

NEXT:
	nextPtr := atomic.LoadPointer(&headNode.next)
	if nextPtr == nil {
		return ErrpointListValueNotFound
	}

	nextNode := (*pointListNode)(nextPtr)

	if pointListCmp(nextNode.val, v) > 0 {
		return ErrpointListValueNotFound
	}

	if pointListCmp(nextNode.val, v) == 0 {
		replacementPtr := atomic.LoadPointer(&nextNode.next)
		if !atomic.CompareAndSwapPointer(&headNode.next, nextPtr, replacementPtr) {
			goto NEXT
		}

		atomic.AddInt32(&l.size, -1)
		return nil
	}

	headNode = nextNode
	goto NEXT
}

// Size returns the number of elements currently in the list.
func (l *pointList) Size() int {
	return int(atomic.LoadInt32(&l.size))
}

// NewIterator returns a new iterator. Values can be read
// after Next is called.
func (l *pointList) NewIterator() *pointListIterator {
	return &pointListIterator{
		list:  l,
		valid: true,
	}
}

// Next positions the iterator at the next node in the list.
// Next will be positioned at the head on the first call.
// The return value will be true if a value can be read from the list.
func (i *pointListIterator) Next() bool {
	if !i.valid {
		return false
	}

	if i.current == nil {
		if i.list.head == nil {
			i.valid = false
			return false
		}

		i.current = (*pointListNode)(i.list.head)
		return true
	}

	i.current = (*pointListNode)(i.current.next)

	i.valid = i.current != nil
	return i.valid
}

// Value reads the value from the current node of the iterator.
// An error is returned if a value cannot be retrieved.
func (i *pointListIterator) Value() (Point, error) {
	var v Point

	if i.current == nil {
		return v, ErrpointListValueNotFound
	}

	return i.current.val, nil
}

// String returns the string representation of the list.
func (l *pointList) String() string {
	output := ""

	if l.head == nil {
		return output
	}

	i := l.NewIterator()

	for i.Next() {
		v, _ := i.Value()
		output += fmt.Sprintf("%v ", v)
	}

	return output
}
